/******************************************************************************
 * Copyright 2024 TypeFox GmbH
 * This program and the accompanying materials are made available under the
 * terms of the MIT License, which is available in the project root.
 ******************************************************************************/

import type { Grammar } from '../languages/generated/ast.js';

/**
 * Translates a Langium Grammar AST into a backend's native grammar format.
 * Each backend package provides an implementation.
 * Called at build time by langium-cli.
 */
export interface GrammarTranslator {
    /** Backend name (e.g., "chevrotain", "lezer", "tree-sitter"). */
    readonly backend: string;

    /**
     * Validate that the grammar is compatible with this backend.
     * Returns diagnostics for unsupported features.
     *
     * Example: `conflicts` block with Chevrotain → error diagnostic.
     * Example: `external tokens` without corresponding .c file for Tree-sitter → error.
     */
    validate(grammar: Grammar): TranslationDiagnostic[];

    /**
     * Translate the grammar and write output file(s).
     *
     * - Chevrotain: serialize grammar JSON (runtime interpretation)
     * - Lezer: write .grammar file, run @lezer/generator → parse tables JS
     * - Tree-sitter: write grammar.js, run tree-sitter generate → WASM
     */
    translate(grammar: Grammar, outputDir: string): Promise<TranslationResult>;
}

/**
 * A diagnostic produced during grammar translation.
 */
export interface TranslationDiagnostic {
    readonly message: string;
    readonly severity: 'error' | 'warning' | 'info';
    /** The grammar element that triggered this diagnostic. */
    readonly source?: string;
    /** Suggestion for fixing the issue. */
    readonly suggestion?: string;
}

/**
 * The result of a grammar translation operation.
 */
export interface TranslationResult {
    /** Files generated by translation. */
    readonly outputFiles: string[];
    /** Any diagnostics produced during translation. */
    readonly diagnostics: TranslationDiagnostic[];
}
